/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesmanRouteRouteImport } from './routes/salesman/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesmanIndexRouteImport } from './routes/salesman/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DoctorCustomerIndexRouteImport } from './routes/doctor-customer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SalesmanTransactionRouteImport } from './routes/salesman/transaction'
import { Route as SalesmanQuoteRouteImport } from './routes/salesman/quote'
import { Route as SalesmanOverviewRouteImport } from './routes/salesman/overview'
import { Route as SalesmanInvoicesRouteImport } from './routes/salesman/invoices'
import { Route as SalesmanInventoryRouteImport } from './routes/salesman/inventory'
import { Route as AdminUpdateUserRouteImport } from './routes/admin/update-user'
import { Route as AdminCreateUserRouteImport } from './routes/admin/create-user'

const SalesmanRouteRoute = SalesmanRouteRouteImport.update({
  id: '/salesman',
  path: '/salesman',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesmanIndexRoute = SalesmanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorCustomerIndexRoute = DoctorCustomerIndexRouteImport.update({
  id: '/doctor-customer/',
  path: '/doctor-customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SalesmanTransactionRoute = SalesmanTransactionRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const SalesmanQuoteRoute = SalesmanQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const SalesmanOverviewRoute = SalesmanOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const SalesmanInvoicesRoute = SalesmanInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const SalesmanInventoryRoute = SalesmanInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const AdminUpdateUserRoute = AdminUpdateUserRouteImport.update({
  id: '/update-user',
  path: '/update-user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreateUserRoute = AdminCreateUserRouteImport.update({
  id: '/create-user',
  path: '/create-user',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/salesman': typeof SalesmanRouteRouteWithChildren
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/update-user': typeof AdminUpdateUserRoute
  '/salesman/inventory': typeof SalesmanInventoryRoute
  '/salesman/invoices': typeof SalesmanInvoicesRoute
  '/salesman/overview': typeof SalesmanOverviewRoute
  '/salesman/quote': typeof SalesmanQuoteRoute
  '/salesman/transaction': typeof SalesmanTransactionRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor-customer/': typeof DoctorCustomerIndexRoute
  '/login/': typeof LoginIndexRoute
  '/salesman/': typeof SalesmanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/update-user': typeof AdminUpdateUserRoute
  '/salesman/inventory': typeof SalesmanInventoryRoute
  '/salesman/invoices': typeof SalesmanInvoicesRoute
  '/salesman/overview': typeof SalesmanOverviewRoute
  '/salesman/quote': typeof SalesmanQuoteRoute
  '/salesman/transaction': typeof SalesmanTransactionRoute
  '/admin': typeof AdminIndexRoute
  '/doctor-customer': typeof DoctorCustomerIndexRoute
  '/login': typeof LoginIndexRoute
  '/salesman': typeof SalesmanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/salesman': typeof SalesmanRouteRouteWithChildren
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/update-user': typeof AdminUpdateUserRoute
  '/salesman/inventory': typeof SalesmanInventoryRoute
  '/salesman/invoices': typeof SalesmanInvoicesRoute
  '/salesman/overview': typeof SalesmanOverviewRoute
  '/salesman/quote': typeof SalesmanQuoteRoute
  '/salesman/transaction': typeof SalesmanTransactionRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor-customer/': typeof DoctorCustomerIndexRoute
  '/login/': typeof LoginIndexRoute
  '/salesman/': typeof SalesmanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/salesman'
    | '/admin/create-user'
    | '/admin/update-user'
    | '/salesman/inventory'
    | '/salesman/invoices'
    | '/salesman/overview'
    | '/salesman/quote'
    | '/salesman/transaction'
    | '/admin/'
    | '/doctor-customer/'
    | '/login/'
    | '/salesman/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/create-user'
    | '/admin/update-user'
    | '/salesman/inventory'
    | '/salesman/invoices'
    | '/salesman/overview'
    | '/salesman/quote'
    | '/salesman/transaction'
    | '/admin'
    | '/doctor-customer'
    | '/login'
    | '/salesman'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/salesman'
    | '/admin/create-user'
    | '/admin/update-user'
    | '/salesman/inventory'
    | '/salesman/invoices'
    | '/salesman/overview'
    | '/salesman/quote'
    | '/salesman/transaction'
    | '/admin/'
    | '/doctor-customer/'
    | '/login/'
    | '/salesman/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SalesmanRouteRoute: typeof SalesmanRouteRouteWithChildren
  DoctorCustomerIndexRoute: typeof DoctorCustomerIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salesman': {
      id: '/salesman'
      path: '/salesman'
      fullPath: '/salesman'
      preLoaderRoute: typeof SalesmanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salesman/': {
      id: '/salesman/'
      path: '/'
      fullPath: '/salesman/'
      preLoaderRoute: typeof SalesmanIndexRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-customer/': {
      id: '/doctor-customer/'
      path: '/doctor-customer'
      fullPath: '/doctor-customer/'
      preLoaderRoute: typeof DoctorCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/salesman/transaction': {
      id: '/salesman/transaction'
      path: '/transaction'
      fullPath: '/salesman/transaction'
      preLoaderRoute: typeof SalesmanTransactionRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/salesman/quote': {
      id: '/salesman/quote'
      path: '/quote'
      fullPath: '/salesman/quote'
      preLoaderRoute: typeof SalesmanQuoteRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/salesman/overview': {
      id: '/salesman/overview'
      path: '/overview'
      fullPath: '/salesman/overview'
      preLoaderRoute: typeof SalesmanOverviewRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/salesman/invoices': {
      id: '/salesman/invoices'
      path: '/invoices'
      fullPath: '/salesman/invoices'
      preLoaderRoute: typeof SalesmanInvoicesRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/salesman/inventory': {
      id: '/salesman/inventory'
      path: '/inventory'
      fullPath: '/salesman/inventory'
      preLoaderRoute: typeof SalesmanInventoryRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/admin/update-user': {
      id: '/admin/update-user'
      path: '/update-user'
      fullPath: '/admin/update-user'
      preLoaderRoute: typeof AdminUpdateUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/create-user': {
      id: '/admin/create-user'
      path: '/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof AdminCreateUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCreateUserRoute: typeof AdminCreateUserRoute
  AdminUpdateUserRoute: typeof AdminUpdateUserRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCreateUserRoute: AdminCreateUserRoute,
  AdminUpdateUserRoute: AdminUpdateUserRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SalesmanRouteRouteChildren {
  SalesmanInventoryRoute: typeof SalesmanInventoryRoute
  SalesmanInvoicesRoute: typeof SalesmanInvoicesRoute
  SalesmanOverviewRoute: typeof SalesmanOverviewRoute
  SalesmanQuoteRoute: typeof SalesmanQuoteRoute
  SalesmanTransactionRoute: typeof SalesmanTransactionRoute
  SalesmanIndexRoute: typeof SalesmanIndexRoute
}

const SalesmanRouteRouteChildren: SalesmanRouteRouteChildren = {
  SalesmanInventoryRoute: SalesmanInventoryRoute,
  SalesmanInvoicesRoute: SalesmanInvoicesRoute,
  SalesmanOverviewRoute: SalesmanOverviewRoute,
  SalesmanQuoteRoute: SalesmanQuoteRoute,
  SalesmanTransactionRoute: SalesmanTransactionRoute,
  SalesmanIndexRoute: SalesmanIndexRoute,
}

const SalesmanRouteRouteWithChildren = SalesmanRouteRoute._addFileChildren(
  SalesmanRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SalesmanRouteRoute: SalesmanRouteRouteWithChildren,
  DoctorCustomerIndexRoute: DoctorCustomerIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
