/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesmanRouteRouteImport } from './routes/salesman/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesmanIndexRouteImport } from './routes/salesman/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DoctorCustomerIndexRouteImport } from './routes/doctor-customer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SalesmanQuoteRouteImport } from './routes/salesman/quote'
import { Route as SalesmanOverviewRouteImport } from './routes/salesman/overview'
import { Route as SalesmanInvoicesRouteImport } from './routes/salesman/invoices'
import { Route as SalesmanInventoryRouteImport } from './routes/salesman/inventory'
import { Route as AdminVariantsIndexRouteImport } from './routes/admin/variants/index'
import { Route as AdminVariantUnitsIndexRouteImport } from './routes/admin/variant-units/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUpdateUserIndexRouteImport } from './routes/admin/update-user/index'
import { Route as AdminUnitsIndexRouteImport } from './routes/admin/units/index'
import { Route as AdminSystemIndexRouteImport } from './routes/admin/system/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminQuotationsIndexRouteImport } from './routes/admin/quotations/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments/index'
import { Route as AdminLotsIndexRouteImport } from './routes/admin/lots/index'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin/invoices/index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin/inventory/index'
import { Route as AdminDueCollectionIndexRouteImport } from './routes/admin/due-collection/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomerLedgerIndexRouteImport } from './routes/admin/customer-ledger/index'
import { Route as AdminCreateUserIndexRouteImport } from './routes/admin/create-user/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminApiInspectorIndexRouteImport } from './routes/admin/api-inspector/index'
import { Route as AdminApiDocsIndexRouteImport } from './routes/admin/api-docs/index'
import { Route as AdminAnalyticsInspectorIndexRouteImport } from './routes/admin/analytics-inspector/index'

const SalesmanRouteRoute = SalesmanRouteRouteImport.update({
  id: '/salesman',
  path: '/salesman',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesmanIndexRoute = SalesmanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorCustomerIndexRoute = DoctorCustomerIndexRouteImport.update({
  id: '/doctor-customer/',
  path: '/doctor-customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SalesmanQuoteRoute = SalesmanQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const SalesmanOverviewRoute = SalesmanOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const SalesmanInvoicesRoute = SalesmanInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const SalesmanInventoryRoute = SalesmanInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SalesmanRouteRoute,
} as any)
const AdminVariantsIndexRoute = AdminVariantsIndexRouteImport.update({
  id: '/variants/',
  path: '/variants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVariantUnitsIndexRoute = AdminVariantUnitsIndexRouteImport.update({
  id: '/variant-units/',
  path: '/variant-units/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUpdateUserIndexRoute = AdminUpdateUserIndexRouteImport.update({
  id: '/update-user/',
  path: '/update-user/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUnitsIndexRoute = AdminUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemIndexRoute = AdminSystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQuotationsIndexRoute = AdminQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLotsIndexRoute = AdminLotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDueCollectionIndexRoute = AdminDueCollectionIndexRouteImport.update({
  id: '/due-collection/',
  path: '/due-collection/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomerLedgerIndexRoute =
  AdminCustomerLedgerIndexRouteImport.update({
    id: '/customer-ledger/',
    path: '/customer-ledger/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCreateUserIndexRoute = AdminCreateUserIndexRouteImport.update({
  id: '/create-user/',
  path: '/create-user/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiInspectorIndexRoute = AdminApiInspectorIndexRouteImport.update({
  id: '/api-inspector/',
  path: '/api-inspector/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiDocsIndexRoute = AdminApiDocsIndexRouteImport.update({
  id: '/api-docs/',
  path: '/api-docs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsInspectorIndexRoute =
  AdminAnalyticsInspectorIndexRouteImport.update({
    id: '/analytics-inspector/',
    path: '/analytics-inspector/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/salesman': typeof SalesmanRouteRouteWithChildren
  '/salesman/inventory': typeof SalesmanInventoryRoute
  '/salesman/invoices': typeof SalesmanInvoicesRoute
  '/salesman/overview': typeof SalesmanOverviewRoute
  '/salesman/quote': typeof SalesmanQuoteRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor-customer/': typeof DoctorCustomerIndexRoute
  '/login/': typeof LoginIndexRoute
  '/salesman/': typeof SalesmanIndexRoute
  '/admin/analytics-inspector/': typeof AdminAnalyticsInspectorIndexRoute
  '/admin/api-docs/': typeof AdminApiDocsIndexRoute
  '/admin/api-inspector/': typeof AdminApiInspectorIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/create-user/': typeof AdminCreateUserIndexRoute
  '/admin/customer-ledger/': typeof AdminCustomerLedgerIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/due-collection/': typeof AdminDueCollectionIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/lots/': typeof AdminLotsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/quotations/': typeof AdminQuotationsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/admin/units/': typeof AdminUnitsIndexRoute
  '/admin/update-user/': typeof AdminUpdateUserIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/variant-units/': typeof AdminVariantUnitsIndexRoute
  '/admin/variants/': typeof AdminVariantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/salesman/inventory': typeof SalesmanInventoryRoute
  '/salesman/invoices': typeof SalesmanInvoicesRoute
  '/salesman/overview': typeof SalesmanOverviewRoute
  '/salesman/quote': typeof SalesmanQuoteRoute
  '/admin': typeof AdminIndexRoute
  '/doctor-customer': typeof DoctorCustomerIndexRoute
  '/login': typeof LoginIndexRoute
  '/salesman': typeof SalesmanIndexRoute
  '/admin/analytics-inspector': typeof AdminAnalyticsInspectorIndexRoute
  '/admin/api-docs': typeof AdminApiDocsIndexRoute
  '/admin/api-inspector': typeof AdminApiInspectorIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/create-user': typeof AdminCreateUserIndexRoute
  '/admin/customer-ledger': typeof AdminCustomerLedgerIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/due-collection': typeof AdminDueCollectionIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/lots': typeof AdminLotsIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/quotations': typeof AdminQuotationsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/system': typeof AdminSystemIndexRoute
  '/admin/units': typeof AdminUnitsIndexRoute
  '/admin/update-user': typeof AdminUpdateUserIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/variant-units': typeof AdminVariantUnitsIndexRoute
  '/admin/variants': typeof AdminVariantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/salesman': typeof SalesmanRouteRouteWithChildren
  '/salesman/inventory': typeof SalesmanInventoryRoute
  '/salesman/invoices': typeof SalesmanInvoicesRoute
  '/salesman/overview': typeof SalesmanOverviewRoute
  '/salesman/quote': typeof SalesmanQuoteRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor-customer/': typeof DoctorCustomerIndexRoute
  '/login/': typeof LoginIndexRoute
  '/salesman/': typeof SalesmanIndexRoute
  '/admin/analytics-inspector/': typeof AdminAnalyticsInspectorIndexRoute
  '/admin/api-docs/': typeof AdminApiDocsIndexRoute
  '/admin/api-inspector/': typeof AdminApiInspectorIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/create-user/': typeof AdminCreateUserIndexRoute
  '/admin/customer-ledger/': typeof AdminCustomerLedgerIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/due-collection/': typeof AdminDueCollectionIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/lots/': typeof AdminLotsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/quotations/': typeof AdminQuotationsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/admin/units/': typeof AdminUnitsIndexRoute
  '/admin/update-user/': typeof AdminUpdateUserIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/variant-units/': typeof AdminVariantUnitsIndexRoute
  '/admin/variants/': typeof AdminVariantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/salesman'
    | '/salesman/inventory'
    | '/salesman/invoices'
    | '/salesman/overview'
    | '/salesman/quote'
    | '/admin/'
    | '/doctor-customer/'
    | '/login/'
    | '/salesman/'
    | '/admin/analytics-inspector/'
    | '/admin/api-docs/'
    | '/admin/api-inspector/'
    | '/admin/categories/'
    | '/admin/create-user/'
    | '/admin/customer-ledger/'
    | '/admin/customers/'
    | '/admin/dashboard/'
    | '/admin/due-collection/'
    | '/admin/inventory/'
    | '/admin/invoices/'
    | '/admin/lots/'
    | '/admin/payments/'
    | '/admin/products/'
    | '/admin/quotations/'
    | '/admin/reports/'
    | '/admin/system/'
    | '/admin/units/'
    | '/admin/update-user/'
    | '/admin/users/'
    | '/admin/variant-units/'
    | '/admin/variants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/salesman/inventory'
    | '/salesman/invoices'
    | '/salesman/overview'
    | '/salesman/quote'
    | '/admin'
    | '/doctor-customer'
    | '/login'
    | '/salesman'
    | '/admin/analytics-inspector'
    | '/admin/api-docs'
    | '/admin/api-inspector'
    | '/admin/categories'
    | '/admin/create-user'
    | '/admin/customer-ledger'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/due-collection'
    | '/admin/inventory'
    | '/admin/invoices'
    | '/admin/lots'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/quotations'
    | '/admin/reports'
    | '/admin/system'
    | '/admin/units'
    | '/admin/update-user'
    | '/admin/users'
    | '/admin/variant-units'
    | '/admin/variants'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/salesman'
    | '/salesman/inventory'
    | '/salesman/invoices'
    | '/salesman/overview'
    | '/salesman/quote'
    | '/admin/'
    | '/doctor-customer/'
    | '/login/'
    | '/salesman/'
    | '/admin/analytics-inspector/'
    | '/admin/api-docs/'
    | '/admin/api-inspector/'
    | '/admin/categories/'
    | '/admin/create-user/'
    | '/admin/customer-ledger/'
    | '/admin/customers/'
    | '/admin/dashboard/'
    | '/admin/due-collection/'
    | '/admin/inventory/'
    | '/admin/invoices/'
    | '/admin/lots/'
    | '/admin/payments/'
    | '/admin/products/'
    | '/admin/quotations/'
    | '/admin/reports/'
    | '/admin/system/'
    | '/admin/units/'
    | '/admin/update-user/'
    | '/admin/users/'
    | '/admin/variant-units/'
    | '/admin/variants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SalesmanRouteRoute: typeof SalesmanRouteRouteWithChildren
  DoctorCustomerIndexRoute: typeof DoctorCustomerIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salesman': {
      id: '/salesman'
      path: '/salesman'
      fullPath: '/salesman'
      preLoaderRoute: typeof SalesmanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salesman/': {
      id: '/salesman/'
      path: '/'
      fullPath: '/salesman/'
      preLoaderRoute: typeof SalesmanIndexRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-customer/': {
      id: '/doctor-customer/'
      path: '/doctor-customer'
      fullPath: '/doctor-customer/'
      preLoaderRoute: typeof DoctorCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/salesman/quote': {
      id: '/salesman/quote'
      path: '/quote'
      fullPath: '/salesman/quote'
      preLoaderRoute: typeof SalesmanQuoteRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/salesman/overview': {
      id: '/salesman/overview'
      path: '/overview'
      fullPath: '/salesman/overview'
      preLoaderRoute: typeof SalesmanOverviewRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/salesman/invoices': {
      id: '/salesman/invoices'
      path: '/invoices'
      fullPath: '/salesman/invoices'
      preLoaderRoute: typeof SalesmanInvoicesRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/salesman/inventory': {
      id: '/salesman/inventory'
      path: '/inventory'
      fullPath: '/salesman/inventory'
      preLoaderRoute: typeof SalesmanInventoryRouteImport
      parentRoute: typeof SalesmanRouteRoute
    }
    '/admin/variants/': {
      id: '/admin/variants/'
      path: '/variants'
      fullPath: '/admin/variants/'
      preLoaderRoute: typeof AdminVariantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/variant-units/': {
      id: '/admin/variant-units/'
      path: '/variant-units'
      fullPath: '/admin/variant-units/'
      preLoaderRoute: typeof AdminVariantUnitsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/update-user/': {
      id: '/admin/update-user/'
      path: '/update-user'
      fullPath: '/admin/update-user/'
      preLoaderRoute: typeof AdminUpdateUserIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/units/': {
      id: '/admin/units/'
      path: '/units'
      fullPath: '/admin/units/'
      preLoaderRoute: typeof AdminUnitsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system/': {
      id: '/admin/system/'
      path: '/system'
      fullPath: '/admin/system/'
      preLoaderRoute: typeof AdminSystemIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/quotations/': {
      id: '/admin/quotations/'
      path: '/quotations'
      fullPath: '/admin/quotations/'
      preLoaderRoute: typeof AdminQuotationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lots/': {
      id: '/admin/lots/'
      path: '/lots'
      fullPath: '/admin/lots/'
      preLoaderRoute: typeof AdminLotsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/due-collection/': {
      id: '/admin/due-collection/'
      path: '/due-collection'
      fullPath: '/admin/due-collection/'
      preLoaderRoute: typeof AdminDueCollectionIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customer-ledger/': {
      id: '/admin/customer-ledger/'
      path: '/customer-ledger'
      fullPath: '/admin/customer-ledger/'
      preLoaderRoute: typeof AdminCustomerLedgerIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/create-user/': {
      id: '/admin/create-user/'
      path: '/create-user'
      fullPath: '/admin/create-user/'
      preLoaderRoute: typeof AdminCreateUserIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-inspector/': {
      id: '/admin/api-inspector/'
      path: '/api-inspector'
      fullPath: '/admin/api-inspector/'
      preLoaderRoute: typeof AdminApiInspectorIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-docs/': {
      id: '/admin/api-docs/'
      path: '/api-docs'
      fullPath: '/admin/api-docs/'
      preLoaderRoute: typeof AdminApiDocsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics-inspector/': {
      id: '/admin/analytics-inspector/'
      path: '/analytics-inspector'
      fullPath: '/admin/analytics-inspector/'
      preLoaderRoute: typeof AdminAnalyticsInspectorIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsInspectorIndexRoute: typeof AdminAnalyticsInspectorIndexRoute
  AdminApiDocsIndexRoute: typeof AdminApiDocsIndexRoute
  AdminApiInspectorIndexRoute: typeof AdminApiInspectorIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCreateUserIndexRoute: typeof AdminCreateUserIndexRoute
  AdminCustomerLedgerIndexRoute: typeof AdminCustomerLedgerIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDueCollectionIndexRoute: typeof AdminDueCollectionIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminLotsIndexRoute: typeof AdminLotsIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminQuotationsIndexRoute: typeof AdminQuotationsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSystemIndexRoute: typeof AdminSystemIndexRoute
  AdminUnitsIndexRoute: typeof AdminUnitsIndexRoute
  AdminUpdateUserIndexRoute: typeof AdminUpdateUserIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVariantUnitsIndexRoute: typeof AdminVariantUnitsIndexRoute
  AdminVariantsIndexRoute: typeof AdminVariantsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsInspectorIndexRoute: AdminAnalyticsInspectorIndexRoute,
  AdminApiDocsIndexRoute: AdminApiDocsIndexRoute,
  AdminApiInspectorIndexRoute: AdminApiInspectorIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCreateUserIndexRoute: AdminCreateUserIndexRoute,
  AdminCustomerLedgerIndexRoute: AdminCustomerLedgerIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDueCollectionIndexRoute: AdminDueCollectionIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminLotsIndexRoute: AdminLotsIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminQuotationsIndexRoute: AdminQuotationsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSystemIndexRoute: AdminSystemIndexRoute,
  AdminUnitsIndexRoute: AdminUnitsIndexRoute,
  AdminUpdateUserIndexRoute: AdminUpdateUserIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVariantUnitsIndexRoute: AdminVariantUnitsIndexRoute,
  AdminVariantsIndexRoute: AdminVariantsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SalesmanRouteRouteChildren {
  SalesmanInventoryRoute: typeof SalesmanInventoryRoute
  SalesmanInvoicesRoute: typeof SalesmanInvoicesRoute
  SalesmanOverviewRoute: typeof SalesmanOverviewRoute
  SalesmanQuoteRoute: typeof SalesmanQuoteRoute
  SalesmanIndexRoute: typeof SalesmanIndexRoute
}

const SalesmanRouteRouteChildren: SalesmanRouteRouteChildren = {
  SalesmanInventoryRoute: SalesmanInventoryRoute,
  SalesmanInvoicesRoute: SalesmanInvoicesRoute,
  SalesmanOverviewRoute: SalesmanOverviewRoute,
  SalesmanQuoteRoute: SalesmanQuoteRoute,
  SalesmanIndexRoute: SalesmanIndexRoute,
}

const SalesmanRouteRouteWithChildren = SalesmanRouteRoute._addFileChildren(
  SalesmanRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SalesmanRouteRoute: SalesmanRouteRouteWithChildren,
  DoctorCustomerIndexRoute: DoctorCustomerIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
